import { slugify } from "@/lib/utils";

export const STATIC_OPPORTUNITIES = [
  {
    title: "Google for Startups — Cloud Program",
    organization: "Google",
    location: "Global / Remote",
    category: "business",
    eligibility: "Eligible startups per Google criteria",
    summary: "Cloud credits and support for startups. Verify current eligibility on the official page.",
    source_name: "Google for Startups",
    official_url: "https://startup.google.com/",
  },
  {
    title: "GitHub Education Student Developer Pack",
    organization: "GitHub",
    location: "Global",
    category: "learning",
    eligibility: "Verified students",
    summary: "Free developer tools for students. Apply with school verification.",
    source_name: "GitHub Education",
    official_url: "https://education.github.com/pack",
  },
  {
    title: "Microsoft Learn Student Hub",
    organization: "Microsoft",
    location: "Global",
    category: "learning",
    eligibility: "Students and learners",
    summary: "Learning paths and student benefits from Microsoft Learn.",
    source_name: "Microsoft Learn",
    official_url: "https://learn.microsoft.com/training/student-hub/",
  },
  {
    title: "AWS Educate",
    organization: "Amazon Web Services",
    location: "Global",
    category: "learning",
    eligibility: "Students and educators",
    summary: "Cloud learning resources for learners. Confirm availability in your region.",
    source_name: "AWS",
    official_url: "https://aws.amazon.com/education/awseducate/",
  },
  {
    title: "MyGov India — Contests & Opportunities",
    organization: "Government of India",
    location: "India",
    category: "government",
    eligibility: "As per each contest",
    summary: "Official Government of India platform for contests and citizen engagement.",
    source_name: "MyGov",
    official_url: "https://www.mygov.in/",
  },
  {
    title: "NASSCOM — Industry resources",
    organization: "NASSCOM",
    location: "India",
    category: "jobs",
    eligibility: "Varies by role",
    summary: "Industry body resources for India's tech sector. Verify roles on employer sites.",
    source_name: "NASSCOM",
    official_url: "https://nasscom.in/",
  },
  {
    title: "Wellfound — Startup jobs",
    organization: "Wellfound",
    location: "Remote / Global",
    category: "jobs",
    eligibility: "Open applications",
    summary: "Startup job board. Listings change frequently; apply via official postings only.",
    source_name: "Wellfound",
    official_url: "https://wellfound.com/",
  },
  {
    title: "AICTE India",
    organization: "AICTE",
    location: "India",
    category: "learning",
    eligibility: "Students as per AICTE rules",
    summary: "Academic and internship-related information via AICTE. Confirm on official site.",
    source_name: "AICTE",
    official_url: "https://www.aicte-india.org/",
  },
].map((o) => ({
  ...o,
  slug: slugify(o.title),
  deadline: null as string | null,
  is_active: true,
}));
